In [54]:
import pandas as pd
import numpy as np

In [55]:
df = pd.read_csv('DSBDALExamDataSets/Hepatitis/hepatitis.csv')

In [56]:
df

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.60,?,242,3.3,50,2
151,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.90,126,142,4.3,?,2
152,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.80,75,20,4.1,?,2
153,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.50,81,19,4.1,48,2
154,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.20,100,19,3.1,42,2

In [57]:
df.describe()

            Class         AGE         SEX  ANTIVIRALS   HISTOLOGY
count  155.000000  155.000000  155.000000  155.000000  155.000000
mean     1.793548   41.200000    1.103226    1.845161    1.451613
std      0.406070   12.565878    0.305240    0.362923    0.499266
min      1.000000    7.000000    1.000000    1.000000    1.000000
25%      2.000000   32.000000    1.000000    2.000000    1.000000
50%      2.000000   39.000000    1.000000    2.000000    1.000000
75%      2.000000   50.000000    1.000000    2.000000    2.000000
max      2.000000   78.000000    2.000000    2.000000    2.000000

In [58]:
df.dtypes

Class               int64
AGE                 int64
SEX                 int64
STEROID            object
ANTIVIRALS          int64
FATIGUE            object
MALAISE            object
ANOREXIA           object
LIVER BIG          object
LIVER FIRM         object
SPLEEN PALPABLE    object
SPIDERS            object
ASCITES            object
VARICES            object
BILIRUBIN          object
ALK PHOSPHATE      object
SGOT               object
ALBUMIN            object
PROTIME            object
HISTOLOGY           int64
dtype: object

In [59]:
df['Class'].value_counts()

2    123
1     32
Name: Class, dtype: int64

In [60]:
df['Class'].replace('1','die',inplace=True)
df['Class'].replace('2','live',inplace=True)

In [61]:
df

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.60,?,242,3.3,50,2
151,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.90,126,142,4.3,?,2
152,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.80,75,20,4.1,?,2
153,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.50,81,19,4.1,48,2
154,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.20,100,19,3.1,42,2

In [62]:
df.describe()

            Class         AGE         SEX  ANTIVIRALS   HISTOLOGY
count  155.000000  155.000000  155.000000  155.000000  155.000000
mean     1.793548   41.200000    1.103226    1.845161    1.451613
std      0.406070   12.565878    0.305240    0.362923    0.499266
min      1.000000    7.000000    1.000000    1.000000    1.000000
25%      2.000000   32.000000    1.000000    2.000000    1.000000
50%      2.000000   39.000000    1.000000    2.000000    1.000000
75%      2.000000   50.000000    1.000000    2.000000    2.000000
max      2.000000   78.000000    2.000000    2.000000    2.000000

In [63]:
from sklearn.preprocessing import LabelEncoder
en = LabelEncoder()
for col in df.columns:
    df[col]=en.fit_transform(df[col])

In [64]:
df.dtypes

Class              int64
AGE                int64
SEX                int64
STEROID            int32
ANTIVIRALS         int64
FATIGUE            int32
MALAISE            int32
ANOREXIA           int32
LIVER BIG          int32
LIVER FIRM         int32
SPLEEN PALPABLE    int32
SPIDERS            int32
ASCITES            int32
VARICES            int32
BILIRUBIN          int32
ALK PHOSPHATE      int32
SGOT               int32
ALBUMIN            int32
PROTIME            int32
HISTOLOGY          int64
dtype: object

In [65]:
df.isna().sum()

Class              0
AGE                0
SEX                0
STEROID            0
ANTIVIRALS         0
FATIGUE            0
MALAISE            0
ANOREXIA           0
LIVER BIG          0
LIVER FIRM         0
SPLEEN PALPABLE    0
SPIDERS            0
ASCITES            0
VARICES            0
BILIRUBIN          0
ALK PHOSPHATE      0
SGOT               0
ALBUMIN            0
PROTIME            0
HISTOLOGY          0
dtype: int64

In [66]:
def outliers(df,drop=False):
    for feature in df.columns:
        data = df[feature]
        Q1=np.percentile(data,25.)
        Q3=np.percentile(data,75.)
        IQR = Q3-Q1
        step = IQR*1.5
        outliers = data[~((data>=Q1-step)&(data<=Q3+step))].index.tolist()
        if not drop:
            print('For the feature {}, No of Outliers is {}'.format(feature, len(outliers)))
        if drop:
            df.drop(outliers, inplace = True, errors = 'ignore')
            print('Outliers from {} feature removed'.format(feature))
           
# def outliers(df_out, drop = False):
#   for each_feature in df_out.columns:
#       feature_data = df_out[each_feature]
#       Q1 = np.percentile(feature_data, 25.) # 25th percentile of the data of the given feature
#       Q3 = np.percentile(feature_data, 75.) # 75th percentile of the data of the given feature
#       IQR = Q3-Q1 #Interquartile Range
#       outlier_step = IQR * 2 #That's we were talking about above
#       outliers = feature_data[~((feature_data >= Q1 - outlier_step) & 
#       (feature_data <= Q3 + outlier_step))].index.tolist() 
#       if not drop:
#         print('For the feature {}, No of Outliers is {}'.format(each_feature, len(outliers)))
#       if drop:
#         df.drop(outliers, inplace = True, errors = 'ignore')
#         print('Outliers from {} feature removed'.format(each_feature))

In [67]:
feature = ['Class'
,'AGE'
,'SEX'
,'STEROID'
,'ANTIVIRALS'
,'FATIGUE'
,'MALAISE'
,'ANOREXIA'
,'LIVER BIG'
,'LIVER FIRM'
,'SPLEEN PALPABLE'
,'SPIDERS'
,'ASCITES'
,'VARICES'
,'BILIRUBIN'
,'ALK PHOSPHATE'
,'SGOT'
,'ALBUMIN'
,'PROTIME'
,'HISTOLOGY']

In [68]:
outliers(df[feature])

For the feature Class, No of Outliers is 32
For the feature AGE, No of Outliers is 0
For the feature SEX, No of Outliers is 16
For the feature STEROID, No of Outliers is 0
For the feature ANTIVIRALS, No of Outliers is 24
For the feature FATIGUE, No of Outliers is 0
For the feature MALAISE, No of Outliers is 0
For the feature ANOREXIA, No of Outliers is 33
For the feature LIVER BIG, No of Outliers is 35
For the feature LIVER FIRM, No of Outliers is 0
For the feature SPLEEN PALPABLE, No of Outliers is 35
For the feature SPIDERS, No of Outliers is 0
For the feature ASCITES, No of Outliers is 25
For the feature VARICES, No of Outliers is 23
For the feature BILIRUBIN, No of Outliers is 17
For the feature ALK PHOSPHATE, No of Outliers is 0
For the feature SGOT, No of Outliers is 0
For the feature ALBUMIN, No of Outliers is 0
For the feature PROTIME, No of Outliers is 0
For the feature HISTOLOGY, No of Outliers is 0

In [69]:
feature

['Class',
 'AGE',
 'SEX',
 'STEROID',
 'ANTIVIRALS',
 'FATIGUE',
 'MALAISE',
 'ANOREXIA',
 'LIVER BIG',
 'LIVER FIRM',
 'SPLEEN PALPABLE',
 'SPIDERS',
 'ASCITES',
 'VARICES',
 'BILIRUBIN',
 'ALK PHOSPHATE',
 'SGOT',
 'ALBUMIN',
 'PROTIME',
 'HISTOLOGY']

In [70]:
x=df[feature]
y=df['Class']
df.shape

(155, 20)

In [71]:
x.drop(['Class'],axis=1,inplace=True)

In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=125)

In [73]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [74]:
model.fit(x_train,y_train)

MultinomialNB()

In [75]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [76]:
from sklearn import metrics
print("accuracy  :: ",metrics.accuracy_score(y_pred,y_test))
print("precision :: ",metrics.precision_score(y_pred,y_test))
print("recall    :: ",metrics.recall_score(y_pred,y_test))
print("f1        :: ",metrics.f1_score(y_pred,y_test))

accuracy  ::  0.8709677419354839
precision ::  0.8518518518518519
recall    ::  1.0
f1        ::  0.92

In [77]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [78]:
model.fit(x_train,y_train)

d:\Applications\Python\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [82]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [81]:
from sklearn import metrics
print("accuracy  :: ",metrics.accuracy_score(y_pred,y_test))
print("precision :: ",metrics.precision_score(y_pred,y_test))
print("recall    :: ",metrics.recall_score(y_pred,y_test))
print("f1        :: ",metrics.f1_score(y_pred,y_test))

accuracy  ::  0.8709677419354839
precision ::  0.8518518518518519
recall    ::  1.0
f1        ::  0.92